name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - LICENSE
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - LICENSE

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        pandoc:
          - edge
          - latest
          # This should be the oldest version that's supported
          - 3.2

    container:
      image: pandoc/core:${{ matrix.pandoc }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: apk add build-base git lua5.4-dev luarocks5.4 zip

      - name: Install Lua dependencies
        run: luarocks-5.4 install lunamark

      - name: Test
        run: make test
